// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenderAI.Infrastructure.Data;

#nullable disable

namespace TenderAI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251101065134_AddTenderResultsForPhase2")]
    partial class AddTenderResultsForPhase2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenderAI.Domain.Entities.BftcItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("HistoricalAveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("HistoricalMaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("HistoricalMinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("HistoricalTenderCount")
                        .HasColumnType("integer");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("UserUnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.HasIndex("TenderId", "ItemNumber");

                    b.ToTable("BftcItems");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.DocumentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AnalysisDuration")
                        .HasColumnType("double precision");

                    b.Property<string>("AnalysisModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnalysisText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BftcTableData")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FinancialRisks")
                        .HasColumnType("text");

                    b.Property<string>("KeyPoints")
                        .HasColumnType("text");

                    b.Property<string>("LegalRisks")
                        .HasColumnType("text");

                    b.Property<string>("OperationalRisks")
                        .HasColumnType("text");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAt");

                    b.HasIndex("DocumentId");

                    b.HasIndex("RiskLevel");

                    b.ToTable("DocumentAnalyses");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.HistoricalBftcItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HistoricalTenderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalTenderId");

                    b.ToTable("HistoricalBftcItems");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.HistoricalTender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BidderCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ContractAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("IKN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OkasCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TenderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WinnerCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IKN");

                    b.HasIndex("OkasCode");

                    b.HasIndex("Province");

                    b.HasIndex("TenderDate");

                    b.ToTable("HistoricalTenders");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.PriceAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CompetitivePosition")
                        .HasColumnType("text");

                    b.Property<decimal?>("CompetitiveRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("HistoricalAverageBid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ProfitMarginAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ProfitMarginRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendationReason")
                        .HasColumnType("text");

                    b.Property<decimal>("RecommendedBidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RiskAdjustedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RiskMarginAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RiskMarginRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.Property<double?>("WinProbability")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TenderId")
                        .IsUnique();

                    b.ToTable("PriceAnalyses");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.RiskAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AdvancePaymentRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("AnalysisSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DelayPenaltyRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("DeliveryDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalGuaranteeRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<double>("FinancialRiskScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasAdvancePayment")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPriceAdjustment")
                        .HasColumnType("boolean");

                    b.Property<double>("LegalRiskScore")
                        .HasColumnType("double precision");

                    b.Property<double>("OperationalRiskScore")
                        .HasColumnType("double precision");

                    b.Property<int?>("PaymentTermDays")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredIsoCertificates")
                        .HasColumnType("text");

                    b.Property<int?>("RequiredSimilarWorkCount")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredTseCertificates")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresInstallation")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresSimilarWorkCertificate")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresTraining")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TemporaryGuaranteeRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalRiskScore")
                        .HasColumnType("double precision");

                    b.Property<int?>("WarrantyMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenderId")
                        .IsUnique();

                    b.ToTable("RiskAnalyses");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TechnicalAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedOperationalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MissingProducts")
                        .HasColumnType("text");

                    b.Property<double>("TechnicalCompatibilityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("TechnicalRequirementsSummary")
                        .HasColumnType("text");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenderId")
                        .IsUnique();

                    b.ToTable("TechnicalAnalyses");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TechnicalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptsEquivalent")
                        .HasColumnType("boolean");

                    b.Property<double?>("CompatibilityScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasBrandRequirement")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MatchedUserProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("RequiredBrand")
                        .HasColumnType("text");

                    b.Property<Guid>("TechnicalAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicalSpecifications")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalAnalysisId");

                    b.ToTable("TechnicalItems");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.Tender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdministrativeSpecPdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("AuthorityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BftcPdfUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("BidDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractDraftPdfUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("EkapId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("IKN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsElectronic")
                        .HasColumnType("boolean");

                    b.Property<string>("OkasCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OpeningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcurementMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalSpecPdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BidDeadline");

                    b.HasIndex("IKN")
                        .IsUnique();

                    b.HasIndex("OkasCode");

                    b.HasIndex("Province");

                    b.HasIndex("Status");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnnouncementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenderId", "AnnouncementType");

                    b.ToTable("TenderAnnouncements");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDownloaded");

                    b.HasIndex("TenderId");

                    b.HasIndex("TenderId", "DocumentType");

                    b.ToTable("TenderDocuments");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AwardDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ContractAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IKN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfBidders")
                        .HasColumnType("integer");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WinnerCompany")
                        .HasColumnType("text");

                    b.Property<string>("WinnerTaxNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AwardDate");

                    b.HasIndex("IKN");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("Status");

                    b.HasIndex("TenderId");

                    b.ToTable("TenderResults");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderResultItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("TechnicalSpecs")
                        .HasColumnType("text");

                    b.Property<Guid>("TenderResultId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("TenderResultId");

                    b.HasIndex("TenderResultId", "ItemNumber");

                    b.ToTable("TenderResultItems");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.UserProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalSpecifications")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("UserId");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.BftcItem", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.Tender", "Tender")
                        .WithMany("BftcItems")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.DocumentAnalysis", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.TenderDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.HistoricalBftcItem", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.HistoricalTender", "HistoricalTender")
                        .WithMany("BftcItems")
                        .HasForeignKey("HistoricalTenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricalTender");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.PriceAnalysis", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.Tender", "Tender")
                        .WithOne("PriceAnalysis")
                        .HasForeignKey("TenderAI.Domain.Entities.PriceAnalysis", "TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.RiskAnalysis", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.Tender", "Tender")
                        .WithOne("RiskAnalysis")
                        .HasForeignKey("TenderAI.Domain.Entities.RiskAnalysis", "TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TechnicalAnalysis", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.Tender", "Tender")
                        .WithOne("TechnicalAnalysis")
                        .HasForeignKey("TenderAI.Domain.Entities.TechnicalAnalysis", "TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TechnicalItem", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.TechnicalAnalysis", "TechnicalAnalysis")
                        .WithMany("TechnicalItems")
                        .HasForeignKey("TechnicalAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnicalAnalysis");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderAnnouncement", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.Tender", "Tender")
                        .WithMany("Announcements")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderDocument", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.Tender", "Tender")
                        .WithMany("Documents")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderResult", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.Tender", "Tender")
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderResultItem", b =>
                {
                    b.HasOne("TenderAI.Domain.Entities.TenderResult", "TenderResult")
                        .WithMany("Items")
                        .HasForeignKey("TenderResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderResult");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.HistoricalTender", b =>
                {
                    b.Navigation("BftcItems");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TechnicalAnalysis", b =>
                {
                    b.Navigation("TechnicalItems");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.Tender", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("BftcItems");

                    b.Navigation("Documents");

                    b.Navigation("PriceAnalysis");

                    b.Navigation("RiskAnalysis");

                    b.Navigation("TechnicalAnalysis");
                });

            modelBuilder.Entity("TenderAI.Domain.Entities.TenderResult", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
